describe("Test Example Function", () => {
  it("should run without error", () => {
    try {
      console.log("exampl;e");
    } catch (error) {}
  });
});
