describe("Test Example Function", () => {
  it("should run without error", () => {
    try {
      console.log("example");
    } catch (error) {
      console.log("bug");
    }
  });
});
